const express = require('express')
const batchController = require('../controllers/batchdetails.js')
const mockController = require('../controllers/mockratings.js')
const router = express.Router()
const Authonticate = require('../middlewares/auth.js')
router.post('/batchregister',batchController.batchRegister)
router.delete('/deletebatch',batchController.deleteBatch)
router.put('/editbatch',batchController.batchEdit)
router.get('/allbatches',batchController.getAllbatches)
router.get('/mentorbatch',batchController.getMentorBatch)
router.post('/mockcreate',mockController.createMock)
router.post('/mockrating',mockController.mockRating)
router.get('/allmockdetails',mockController.getAllMockDetails)
router.get('/employeemockdetails',mockController.getMockDetailsBasedOnEmployee)
module.exports = router